from openpyxl import load_workbook
from pathlib import Path
from datetime import date
p=Path('outputs/backlink-outreach-progress-2026-09-23.xlsx'); wb=load_workbook(p)
ws=wb['Prospects']; log=wb['Submission Log']
ws.append(['Live Northwest BC','Canada / Northwest BC','Local newcomers / jobs / relocation','Story submission form','https://www.livenorthwestbc.ca/submit-a-story/','https://www.livenorthwestbc.ca/submit-a-story/','Direct story form; local editorial review','Not suitable for current author','Fresh prospect','Current form seeks stories from passionate locals living in Northwest BC, especially local newcomer success stories. CMG is not submitting a first-person local story, so this is not a suitable route for the current campaign.','Not independently verified; do not assume dofollow','Inspected 2026-09-23; excluded on author-fit grounds'])
log.append(['Live Northwest BC','https://www.livenorthwestbc.ca/submit-a-story/','Local story form','Unsuitable; not submitted','https://www.livenorthwestbc.ca/submit-a-story/','Current rules focus on passionate locals living in Northwest BC and local newcomer success stories. No suitable CMG-authored story available.','Exclude unless an eligible local author/story is provided.',date(2026,9,23)])
ws.append(['Cold Tea Collective','Canada / North American Asian diaspora','Immigration / Asian millennial experience','Contributor pitch form','https://coldteacollective.com/share-your-story/','https://coldteacollective.com/share-your-story/','Pitch form with CAPTCHA; editorial review','Blocked; CAPTCHA required','Fresh prospect','Current page welcomes meaningful personal or community stories but rejects excessively self-promotional marketing and requires CAPTCHA. No attempt made; do not bypass CAPTCHA.','Not independently verified; do not assume dofollow','Inspected 2026-09-23; blocked by CAPTCHA and author-fit requirements'])
log.append(['Cold Tea Collective','https://coldteacollective.com/share-your-story/','Contributor pitch form; CAPTCHA','Blocked; not submitted','https://coldteacollective.com/share-your-story/','Live pitch form requires CAPTCHA and the current CMG commercial pitch would conflict with its anti-self-promotion guidance. CAPTCHA not attempted or bypassed.','Exclude unless a genuine eligible personal/community story and human CAPTCHA completion are available.',date(2026,9,23)])
wb.save(p); print(p.resolve())
