import fs from 'node:fs/promises';
import { FileBlob, SpreadsheetFile } from '@oai/artifact-tool';
const path='outputs/2026-09-20-directory-prospects/commonwealth-migration-free-directory-prospects.xlsx';
const wb=await SpreadsheetFile.importXlsx(await FileBlob.load(path)); const sh=wb.worksheets.getItem('Directory Prospects');
const add=[
['Priority','The Business Listing UK','https://www.thebusinesslisting.co.uk/','https://www.thebusinesslisting.co.uk/','UK professional services','Free forever','UK business details, category and town; remote/service-area fit should be checked','UK-facing discovery and profile opportunity for UK-to-Australia prospects','Site states lifetime listing is free; confirm profile website field at signup.','https://www.thebusinesslisting.co.uk/','Not started','UK clients → Australia','High relevance'],
['Priority','Bizzr UK','https://bizzr.uk/','https://bizzr.uk/','UK professional services','Free core listing','UK business details, town/postcode and category','UK local profile with website field and service description','Site states free core listing includes website and profile description.','https://bizzr.uk/','Not started','UK clients → Australia','High relevance'],
['Priority','Business Backlinks UK','https://www.businessbacklinks.co.uk/','https://www.businessbacklinks.co.uk/','UK business directory','Free listing','Business name, category and location','Explicit UK free business directory; likely website/backlink profile','Site says advertise completely free; verify moderation and link attributes.','https://www.businessbacklinks.co.uk/','Not started','UK clients → Australia','High relevance'],
['Secondary','BizBranches UK','https://bizbranches.uk/add','https://bizbranches.uk/','UK business directory','Free listing','Real UK business, location, category and honest description','Local UK profile; useful only if UK presence/service area is accurately represented','Site states free UK listing; no keyword stuffing or misleading claims.','https://bizbranches.uk/add','Not started','UK clients → Australia','Relevant if UK service presence'],
['Secondary','AddListing.co.uk','https://addlisting.co.uk/','https://addlisting.co.uk/','UK business directory','Free listing','Business details and category','General UK business listing with potential website link','Site advertises free listings; confirm current approval and link policy.','https://addlisting.co.uk/','Not started','UK clients → Australia','Relevant if accepted'],
['Secondary','Noticed.uk','https://noticed.uk/signup','https://noticed.uk/','UK local business','Free listing / approval','Business details; listing reviewed before publishing','UK profile with services, hours, photos and social links','Signup page states listings are checked before going live; confirm website field.','https://noticed.uk/signup','Not started','UK clients → Australia','Relevant if accepted'],
['Secondary','VibeDex UK','https://vibedex.life/for-business','https://vibedex.life/','UK local business','Free listing','UK business serving local customers','Local service profile with website/contact details','Site states UK businesses can add a business free; confirm Australian immigration category fit.','https://vibedex.life/for-business','Not started','UK clients → Australia','Relevant if accepted'],
['Secondary','Business Directory UK','https://www.business-directory.org.uk/addbusiness/','https://www.business-directory.org.uk/','UK business directory','Free listing option','Business details and category; prohibited categories apply','General UK citation/profile','Page provides add-business options; confirm free tier and website field.','https://www.business-directory.org.uk/addbusiness/','Not started','UK clients → Australia','Relevant if accepted'],
['Priority','Yellow Pages Australia','https://www.yellowpages.com.au/','https://www.yellowpages.com.au/','Australia business directory','Free basic listing to confirm','Australian business details and verification','Australia citation/profile if the firm has an Australian office or eligible service presence','Do not invent an Australian address; verify current free listing path.','https://www.yellowpages.com.au/','Not started','Australia migration / international','Only if eligible'],
['Secondary','True Local Australia','https://www.truelocal.com.au/','https://www.truelocal.com.au/','Australia local business','Free listing/claim to confirm','Accurate Australian location or service-area eligibility','Australian local profile and reviews','Confirm free claim and website field before submission.','https://www.truelocal.com.au/','Not started','Australia migration / international','Only if eligible'],
['Secondary','Locanto Australia Services','https://www.locanto.com.au/','https://www.locanto.com.au/','Australia services classifieds','Free ad/listing','Account, service location and compliant description','Classified service listing; traffic opportunity, backlink value uncertain','Use cautiously and only with a truthful professional service listing; renewals may apply.','https://www.locanto.com.au/','Not started','Australia migration / international','Use cautiously'],
['Secondary','AussieWeb','https://www.aussieweb.com.au/','https://www.aussieweb.com.au/','Australia business directory','Free listing/claim to confirm','Business details and category','Australia-focused business citation','Confirm current free listing and link policy.','https://www.aussieweb.com.au/','Not started','Australia migration / international','Only if eligible'],
['Secondary','StartLocal Australia','https://www.startlocal.com.au/','https://www.startlocal.com.au/','Australia local directory','Free listing/claim to confirm','Business and location details','Australian local discovery profile','Confirm current submission flow and whether website links are available.','https://www.startlocal.com.au/','Not started','Australia migration / international','Only if eligible'],
['Secondary','Hotfrog Australia','https://www.hotfrog.com.au/','https://www.hotfrog.com.au/','Australia business directory','Free basic listing to confirm','Business registration and verification','General Australian citation/profile','Check free basic listing at submission; paid visibility may be offered.','https://www.hotfrog.com.au/','Not started','Australia migration / international','Only if eligible'],
['Secondary','Cylex Australia','https://www.cylex-australia.com.au/','https://www.cylex-australia.com.au/','Australia business directory','Free listing to confirm','Business details and email verification','General Australian directory profile','Confirm free listing, moderation and website-link treatment.','https://www.cylex-australia.com.au/','Not started','Australia migration / international','Only if eligible'],
['Priority','Brampton Board of Trade','https://www.bramptonbot.com/','https://www.bramptonbot.com/','Brampton / Canada business community','Directory/membership terms to verify','Business operating in or serving Brampton; membership may be required','Local trust and referral opportunity; stronger than generic SEO directories','Check whether public member directory listing is included and whether membership is paid.','https://www.bramptonbot.com/','Not started','Brampton/Canada → Australia','Local trust opportunity'],
['Priority','Brampton.ca business resources','https://www.brampton.ca/','https://www.brampton.ca/','Brampton / Canada official resources','Official resource; listing eligibility to verify','Must meet any city program or local-business criteria','Potential local trust/resource citation; not a guaranteed backlink directory','Do not submit to unrelated city pages; look for eligible business programs/resources only.','https://www.brampton.ca/','Not started','Brampton/Canada → Australia','Eligibility check'],
['Secondary','411.ca','https://411.ca/','https://411.ca/','Canada local directory','Free basic listing/claim to confirm','Canadian business details and verification','Canadian citation and discovery profile','Confirm current free listing and website field.','https://411.ca/','Not started','Brampton/Canada → Australia','High local relevance'],
['Secondary','n49 Canada','https://www.n49.com/','https://www.n49.com/','Canada local directory','Free listing to confirm','Business account and details','Canadian local citation/review profile','Confirm current free plan, location eligibility and website link.','https://www.n49.com/','Not started','Brampton/Canada → Australia','High local relevance'],
['Secondary','ProfileCanada','https://www.profilecanada.com/','https://www.profilecanada.com/','Canada business directory','Free profile/claim to confirm','Business details and verification','Canada-focused business profile/citation','Confirm current profile claim and website link policy.','https://www.profilecanada.com/','Not started','Brampton/Canada → Australia','High local relevance'],
['Secondary','Yalwa Canada','https://www.yalwa.ca/','https://www.yalwa.ca/','Canada services directory','Free listing/advert to confirm','Account and service details','Canadian service discovery; backlink value uncertain','Confirm free listing rules and category eligibility.','https://www.yalwa.ca/','Not started','Brampton/Canada → Australia','Relevant if accepted'],
['Secondary','Factual Canada','https://www.factual.ca/','https://www.factual.ca/','Canada business directory','Free listing/claim to confirm','Canadian business details','General citation opportunity','Verify the site is active and accepts new business submissions before using.','https://www.factual.ca/','Not started','Brampton/Canada → Australia','Verify activity first'],
['Secondary','LocalStack Canada','https://localstack.ca/','https://localstack.ca/','Canada local directory','Free listing/claim to confirm','Business details and location','Canadian local business profile','Confirm current availability and website field.','https://localstack.ca/','Not started','Brampton/Canada → Australia','Verify activity first'],
['Secondary','Canadian Trade Index','https://www.canadiantradeindex.com/','https://www.canadiantradeindex.com/','Canada business directory','Free listing/claim to confirm','Canadian business details','Canada trade/business citation','Confirm whether professional immigration services are accepted and whether listing is free.','https://www.canadiantradeindex.com/','Not started','Brampton/Canada → Australia','Verify activity first'],
];
const start=31; sh.getRange('A31:M100').clear({applyTo:'contents'}); sh.getRange(`A${start}:M${start+add.length-1}`).values=add;
sh.getRange(`A${start}:M${start+add.length-1}`).format={font:{size:10,color:'#222222'},wrapText:true,verticalAlignment:'top',rowHeight:72};
sh.getRange(`K${start}:K${start+add.length-1}`).dataValidation={rule:{type:'list',values:['Not started','In progress','Submitted','Live','Rejected','Not eligible','Skip']}};
sh.getRange(`K${start}:K${start+add.length-1}`).format={fill:'#FFF2CC',font:{bold:true,color:'#7F6000'},horizontalAlignment:'center'};
sh.getRange(`C${start}:D${start+add.length-1}`).format.font={color:'#0563C1',underline:'single',size:10};
sh.getRange(`J${start}:J${start+add.length-1}`).format.font={color:'#0563C1',underline:'single',size:10};
const out=await SpreadsheetFile.exportXlsx(wb); await out.save(path);
const check=await wb.inspect({kind:'table',range:`Directory Prospects!A31:M${start+add.length-1}`,include:'values,formulas',tableMaxRows:35,tableMaxCols:13}); console.log(check.ndjson);
const errors=await wb.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!|#SPILL!|#CALC!',options:{useRegex:true,maxResults:100},summary:'final formula error scan'}); console.log(errors.ndjson);
const blob=await wb.render({sheetName:'Directory Prospects',range:'A1:M12',scale:1,format:'png'}); await fs.writeFile('outputs/2026-09-20-directory-prospects/directory-prospects-expanded-preview.png',new Uint8Array(await blob.arrayBuffer()));
console.log('expanded',add.length,'rows');
