import {FileBlob, SpreadsheetFile} from '@oai/artifact-tool';
const path='outputs/2026-09-20-directory-prospects/commonwealth-migration-free-directory-prospects.xlsx';
const wb=await SpreadsheetFile.importXlsx(await FileBlob.load(path));
const sh=wb.worksheets.getItem('Directory Prospects');
const current=sh.getRange('A5:S54').values;
const australia=/australia|\.com\.au|omara|migration alliance|findmigrationagents|immigrationau|yellow pages australia|true local|locanto australia|aussieweb|startlocal|hotfrog australia|cylex australia/i;
const kept=current.filter(r=>!australia.test(`${r[1]} ${r[2]} ${r[3]} ${r[9]}`));
const add=(priority,name,url,home,niche,access,eligibility,value,notes,source,audience,fit)=>[priority,name,url,home,niche,access,eligibility,value,notes,source,'Not started',audience,fit,null,null,null,null,null,null];
const added=[
add('High','Invest Brampton Business Directory','https://investbrampton.ca/business-directory/','https://investbrampton.ca/','Brampton official economic-development directory','Free listing/update route','Brampton business; partner portal review','Official local visibility and relevant business context','Official Brampton page states free listing and external verification.','https://investbrampton.ca/business-directory/','Brampton customers, partners and investors','Strong local fit'),
add('High','Brampton Black Business Directory','https://investbrampton.ca/business-directory/','https://investbrampton.ca/','Brampton Black-owned business directory','Free listing/update route','Black-owned/Black-operated business eligibility applies','Official local niche visibility if eligibility is accurate','Separate directory linked from Invest Brampton; verify eligibility before submission.','https://investbrampton.ca/business-directory/','Brampton Black-business community','Conditional fit'),
add('High','Cataloxy Brampton','https://brampton.cataloxy.com/','https://brampton.cataloxy.com/','Brampton business directory','Free company page','Business owners can add a company for free','Local company page with services, contact details and website','Search result states free company pages and Brampton coverage.','https://brampton.cataloxy.com/','Brampton local searchers','Strong local fit'),
add('High','LocalAIHub Brampton','https://localaihub.ca/directory/brampton','https://localaihub.ca/','Brampton local business directory','Free claim/correction','Claim or correction reviewed for factual accuracy','Potential local citation and profile link','Directory page states free listing claim and no payment required for consideration.','https://localaihub.ca/directory/brampton','Brampton residents searching services','Strong local fit'),
add('High','AllBizCanada Brampton','https://allbizcanada.ca/states/on/cities/brampton','https://allbizcanada.ca/','Brampton business directory','Free add/claim route','Team review/verification after submission','Brampton category and business profile visibility','Directory page says add business is free to visitors and submissions are reviewed.','https://allbizcanada.ca/states/on/cities/brampton','Brampton local searchers','Strong local fit'),
add('High','Brampton Businesses Directory','https://bramptonbusinesses.ca/contact/','https://bramptonbusinesses.ca/','Brampton and GTA directory','Free contact submission route','Directory owner review; CAPTCHA/math field may apply','Local Brampton business mention and possible profile link','Contact page explicitly invites businesses to request listing.','https://bramptonbusinesses.ca/contact/','Brampton and GTA customers','Strong local fit'),
add('Medium','AfroBiz Peel Black-Owned Directory','https://www.afrobiz.ca/business-categories---Peel','https://www.afrobiz.ca/','Peel/Brampton Black-owned business directory','Free listing','Black-owned business eligibility; manual processing','Niche community visibility if eligible','Page states free Peel-region listing and 1–2 business-day review.','https://www.afrobiz.ca/business-categories---Peel','Peel Black-business community','Conditional fit'),
add('Medium','Ontario Business Directory','https://ontariobusinessdir.com/u/company_add.php','https://ontariobusinessdir.com/','Ontario business directory','Free listing','Account sign-up and directory approval','Ontario citation with Brampton location','Source states listing is free; verify account and backlink behavior.','https://ontariobusinessdir.com/u/company_add.php','Ontario and Brampton searchers','Good regional fit'),
add('Medium','AD18 Canada Local Services','https://www.ad18.ca/','https://www.ad18.ca/','Canadian classifieds and local services','Free 60-day listing','Listing duration and category rules apply','Local service exposure including Brampton','Source advertises free posting and Brampton local-services listings.','https://www.ad18.ca/','Brampton/GTA service seekers','Moderate fit'),
add('Medium','Aubaine Canada Directory','https://aubaine.ca/en/directory','https://aubaine.ca/','Canadian local business directory','Free registration and claim','Business account and claim verification','Canadian citation and business micro-site','Source states registration and claiming are free.','https://aubaine.ca/en/directory','Canadian local searchers','Good regional fit'),
add('Medium','GTA Search Brampton','https://www.gtasearch.com/','https://www.gtasearch.com/','GTA business directory','Free add/correction route','Owner confirmation may be required','GTA visibility with Brampton location','Search result advertises free add/update of business details.','https://www.gtasearch.com/','GTA and Brampton customers','Good regional fit'),
add('Medium','LocalShops Brampton','https://localshops.ca/search/ontario/brampton','https://localshops.ca/','Brampton local shops directory','Free add-business route','Directory/editor review','Local discovery and possible website citation','Search result says “Help us build our directory” and “It’s free—Add a Business.”','https://localshops.ca/search/ontario/brampton','Brampton residents','Moderate fit'),
add('Medium','YLM Local Community Directory','https://www.ylm.ca/','https://www.ylm.ca/','Canadian local community directory','Free listing','Business/service listing eligibility','Local profile with keywords and service information','Source states “Add my listing” creates a free directory listing.','https://www.ylm.ca/','Local Canadian searchers','Good regional fit'),
add('Medium','FreshFind Business Directory','https://freshfind.ca/for-businesses','https://freshfind.ca/','Local services directory','Free listing','Primarily local food/service businesses; confirm immigration category','Potential local directory visibility if professional services accepted','Source states $0 listing and free directory setup; category fit requires verification.','https://freshfind.ca/for-businesses','Local customers','Conditional fit'),
add('Medium','Brampton Community Directory - Peel Village Life','https://peelvillagelife.ca/peel-village-businesses','https://peelvillagelife.ca/','Peel Village/Brampton local directory','Free editorial inclusion request','Local-area relevance and editor approval','Neighborhood-level visibility','Page says missing businesses can request to be added at no charge.','https://peelvillagelife.ca/peel-village-businesses','Peel Village and nearby residents','Conditional local fit'),
add('Medium','411 Brampton Business Directory','https://411.ca/business-directory/on/brampton','https://411.ca/','Brampton Canadian directory page','Free claim route to verify','Yellow Pages/411 account may be required','Canadian local citation','Verify claim route and whether website field is public.','https://411.ca/business-directory/on/brampton','Brampton local searchers','Good regional fit'),
add('Medium','N49 Brampton Business Directory','https://www.n49.com/business-directory/brampton-on/','https://www.n49.com/','Brampton Canadian directory page','Free add/claim route to verify','Dashboard account and approval may be required','Local profile and website citation','Verify current dashboard flow before submission.','https://www.n49.com/business-directory/brampton-on/','Brampton local searchers','Good regional fit'),
add('Medium','ZipLeaf Brampton','https://www.zipleaf.ca/Companies/Brampton','https://www.zipleaf.ca/','Brampton business directory','Free claim/listing route to verify','Email verification required','Canadian local business profile','Existing workbook check found one-time email verification for publication.','https://www.zipleaf.ca/Companies/Brampton','Brampton and Canada searchers','Good regional fit'),
add('Medium','ProfileCanada Brampton','https://www.profilecanada.com/browse_by_city.cfm?city=Brampton','https://www.profilecanada.com/','Canadian business profiles','Free add/update route to verify','Step-based submission and verification','Canadian business profile with website field','Existing workbook check found a Canadian add-business form but no confirmation.','https://www.profilecanada.com/browse_by_city.cfm?city=Brampton','Brampton and Canada searchers','Good regional fit'),
add('Medium','Cylex Brampton','https://www.cylex-canada.ca/brampton/','https://www.cylex-canada.ca/','Brampton Canadian directory page','Free add/claim route to verify','Cloudflare/access and approval may apply','Local citation if claim succeeds','Existing workbook check found Cloudflare access blocking; retain as prospect only.','https://www.cylex-canada.ca/brampton/','Brampton local searchers','Good regional fit'),
add('Medium','Hotfrog Brampton','https://www.hotfrog.ca/company/commonwealth-migration-group-inc','https://www.hotfrog.ca/','Canadian business directory','Free claim/listing route to verify','Cloudflare/access and profile approval may apply','Local business profile if accessible','Use only if current Brampton page or add-business route is available.','https://www.hotfrog.ca/','Brampton and Canada searchers','Good regional fit'),
add('Medium','Yelp Brampton','https://www.yelp.ca/search?find_desc=Immigration+Services&find_loc=Brampton%2C+ON','https://www.yelp.ca/','Brampton local services directory','Free claim route to verify','Business verification required','Local discovery and review profile','Use accurate service category; no review manipulation.','https://www.yelp.ca/search?find_desc=Immigration+Services&find_loc=Brampton%2C+ON','Brampton service seekers','Good regional fit'),
add('Medium','CanadaOne Business Directory','https://www.canadaone.com/business/index.html','https://www.canadaone.com/','Canadian business directory','Free add-business route','Canadian business, website and account required','Canadian citation and website field','Existing workbook check found free Canadian add-business form.','https://www.canadaone.com/business/index.html','Canadian business searchers','Good regional fit'),
add('Medium','CanadaBusinessOwners Brampton','https://canadabusinessowners.ca/','https://canadabusinessowners.ca/','Canadian owner directory','Free listing route to verify','Canadian business and form approval','Business-owner visibility with local location','Existing workbook contains the directory; add Brampton-specific route for follow-up.','https://canadabusinessowners.ca/','Canadian business owners','Good regional fit'),
add('Medium','Canada Business Directory Brampton','https://canadabusinessdirectory.net/submit-listing/','https://canadabusinessdirectory.net/','Canadian business directory','Free submission route to verify','Cloudflare/access and approval may apply','Canadian local citation','Existing workbook check found Cloudflare block; retain as prospect only.','https://canadabusinessdirectory.net/submit-listing/','Canadian local searchers','Good regional fit'),
add('Medium','LocalStack Brampton','https://localstack.ca/brampton/','https://localstack.ca/','Canadian local directory','Free claim/listing route to verify','Site availability and approval may apply','Local citation if service remains live','Existing workbook check found DNS failure; retain as prospect only.','https://localstack.ca/brampton/','Brampton local searchers','Good regional fit'),
add('Medium','MarketLister Brampton','https://www.marketlister.ca/','https://www.marketlister.ca/','Canadian business directory','Free business page route to verify','Cloudflare/access and review may apply','Local business-page visibility','Existing workbook check found Cloudflare challenge on free-page route.','https://www.marketlister.ca/','Canadian and Brampton searchers','Good regional fit'),
add('Medium','Cybo Brampton','https://www.cybo.com/CA/brampton/','https://www.cybo.com/','Global/local business directory','Free add/claim route to verify','Business verification and category rules','Local citation with website field if available','Brampton location page is the relevant route; verify current free claim policy.','https://www.cybo.com/CA/brampton/','Brampton local searchers','Moderate fit'),
add('Medium','Infobel Brampton','https://www.infobel.com/en/canada/brampton','https://www.infobel.com/','Canadian business directory','Free add/claim route to verify','Listing verification and category rules','Local business profile','Use only if current page offers a legitimate owner claim or add route.','https://www.infobel.com/en/canada/brampton','Brampton and Canada searchers','Moderate fit'),
add('Medium','WhereOrg Brampton','https://whereorg.com/ca/brampton/','https://whereorg.com/','Canadian business directory','Free add/claim route to verify','Owner verification may apply','Local citation','Verify business category and public website field before submission.','https://whereorg.com/ca/brampton/','Brampton local searchers','Moderate fit'),
add('Medium','Brownbook Brampton','https://www.brownbook.net/businesses/canada/ontario/brampton/','https://www.brownbook.net/','Global local business directory','Free add/claim route to verify','Account and moderation may apply','Local business profile','Verify current free listing terms and no paid-only requirement.','https://www.brownbook.net/businesses/canada/ontario/brampton/','Brampton local searchers','Moderate fit'),
add('Medium','Fyple Brampton','https://www.fyple.ca/company/','https://www.fyple.ca/','Canadian business directory','Free add/claim route to verify','Account and moderation may apply','Canadian local citation','Verify Brampton category and website field in current flow.','https://www.fyple.ca/company/','Brampton and Canada searchers','Moderate fit'),
add('Medium','Tupalo Brampton','https://tupalo.com/en/brampton','https://tupalo.com/','Local business discovery directory','Free add/claim route to verify','Profile verification and moderation may apply','Local discovery profile','Verify that the route supports Canadian businesses and website links.','https://tupalo.com/en/brampton','Brampton local searchers','Moderate fit'),
add('Medium','Opendi Brampton','https://brampton.opendi.ca/','https://brampton.opendi.ca/','Canadian local directory','Free add/claim route to verify','Listing verification and moderation may apply','Local profile and citation','Verify current add-business route before submission.','https://brampton.opendi.ca/','Brampton local searchers','Moderate fit'),
];
const finalRows=[...kept,...added];
const oldEnd=54; const newEnd=4+finalRows.length;
if(newEnd>oldEnd){sh.getRange(`A${oldEnd}:S${newEnd}`).copyFrom(sh.getRange(`A${oldEnd}:S${oldEnd}`),'all');}
sh.getRange(`A5:S${newEnd}`).values=finalRows;
if(newEnd<oldEnd) sh.getRange(`A${newEnd+1}:S${oldEnd}`).clear({applyTo:'contents'});
const out=await SpreadsheetFile.exportXlsx(wb); await out.save(path);
console.log(JSON.stringify({removed:current.length-kept.length,added:added.length,finalRows:finalRows.length,newEnd,path}));
