"use client";

import { useMemo, useState } from "react";
import { AlertTriangle, ArrowLeft, ArrowRight, BarChart3, BookOpen, Calculator, CheckCircle2, Clock3, ExternalLink, FileCheck2, Info, MapPin, RefreshCw, ShieldCheck, Sparkles, Target } from "lucide-react";
import { PNP_PROGRAMS, PNP_PROGRAM_OPTIONS } from "@/data/pnp-programs";
import { evaluatePnpStream, getModeLabel, getStatusLabel, getStream } from "@/lib/pnpCalculators";
import { ToolCard, ToolHeader, ToolOptionButton, ToolProgress, ToolResetButton } from "./ui/ToolPrimitives";

const selectionLabels = {
  score: "Score-based",
  targeted: "Targeted",
  priority: "Priority-based",
  historical: "Historical",
  intake: "Intake",
  "score-plus-priority": "Score + priority",
};

function getDrawParameters(draw) {
  if (!draw) return [];
  const standardParameters = [
    draw.invitations != null ? { label: "Invitations", value: draw.invitations, emphasis: true } : null,
    draw.minimum != null ? { label: "Cutoff / minimum", value: draw.minimum } : null,
    draw.selectionType ? { label: "Selection model", value: selectionLabels[draw.selectionType] || draw.selectionType } : null,
    draw.detail ? { label: "Official draw detail", value: draw.detail } : null,
    draw.selectionCriteria ? { label: "Selection criteria", value: draw.selectionCriteria } : null,
    draw.tieBreaker ? { label: "Tie-breaker", value: draw.tieBreaker } : null,
    draw.applicationWindow ? { label: "Application window", value: draw.applicationWindow } : null,
    draw.eoiValidity ? { label: "EOI validity", value: draw.eoiValidity } : null,
    draw.note ? { label: "Official note", value: draw.note } : null,
  ];
  const customParameters = Array.isArray(draw.parameters) ? draw.parameters : [];
  return [...standardParameters, ...customParameters].filter((parameter) => parameter?.label && parameter?.value != null);
}

function DrawFacts({ draw, featured = false }) {
  const parameters = getDrawParameters(draw);
  return <dl className={featured ? "mt-5 grid gap-2.5 sm:grid-cols-2" : "mt-3 grid gap-2 border-t border-[var(--template-border)] pt-3 sm:grid-cols-2"}>{parameters.map((parameter, index) => <div key={`${parameter.label}-${index}`} className={`min-w-0 rounded-[0.7rem] ${featured ? "border border-white/15 bg-black/10 p-3" : "bg-[color-mix(in_srgb,var(--template-surface)_55%,transparent)] px-3 py-2"}`}><dt className={`text-[0.61rem] font-extrabold uppercase tracking-[0.08em] ${featured ? "text-[color-mix(in_srgb,var(--template-on-primary)_70%,transparent)]" : "text-[var(--template-muted)]"}`}>{parameter.label}</dt><dd className={`m-0 mt-1 break-words leading-[1.4] ${parameter.emphasis ? "text-[1.2rem] font-extrabold" : "text-[0.72rem] font-semibold"} ${featured ? "text-[var(--template-on-primary)]" : "text-[var(--template-ink)]"}`}>{parameter.value}</dd></div>)}</dl>;
}

function getSnapshotStats(program) {
  const baseStats = program.snapshot?.stats || [];
  const latest = program.draws?.[0];
  if (!latest) return baseStats;
  const labelText = baseStats.map((stat) => stat.label.toLowerCase()).join(" | ");
  const hasLabel = (...terms) => terms.some((term) => labelText.includes(term));
  const stale = program.source?.status === "stale";
  const extras = [
    latest.date && !hasLabel("latest draw", "last published draw", "draw date") ? { value: latest.date, label: stale ? "Last published draw" : "Latest draw" } : null,
    latest.minimum && !["Not published", "N/A"].includes(latest.minimum) && !hasLabel("cutoff", "floor") ? { value: latest.minimum, label: stale ? "Last published cutoff" : "Latest cutoff" } : null,
    latest.invitations && latest.invitations !== "Not published" && !hasLabel("ita", "invitation", "laa", "round") ? { value: latest.invitations, label: stale ? "Last published invitations" : "Latest draw invitations" } : null,
    selectionLabels[latest.selectionType] && !hasLabel("selection", "priority") ? { value: selectionLabels[latest.selectionType], label: "Draw model" } : null,
  ].filter(Boolean);
  return [...baseStats, ...extras].slice(0, Math.max(baseStats.length, 6));
}

function StatusBadge({ status, children }) {
  const stale = status === "stale";
  return <span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[0.62rem] font-extrabold uppercase tracking-[0.08em] ${stale ? "border-amber-400/30 bg-amber-400/10 text-amber-200" : "border-emerald-300/25 bg-emerald-300/10 text-emerald-100"}`}><span className={`h-1.5 w-1.5 rounded-full ${stale ? "bg-amber-300" : "bg-emerald-300"}`} aria-hidden="true" />{children}</span>;
}

function sourceDate(source) {
  if (!source?.lastVerifiedAt) return "Not recorded";
  return new Intl.DateTimeFormat("en-CA", { dateStyle: "medium", timeZone: "America/Toronto" }).format(new Date(source.lastVerifiedAt));
}

function SourceMeta({ program, stream }) {
  const source = program.source;
  const status = source?.status || "current";
  const documents = (stream?.documents || []).slice(0, 3);
  const remainingDocuments = Math.max(0, (stream?.documents || []).length - documents.length);
  const improvement = stream?.improvements?.[0] || "Confirm the current stream guide and supporting evidence.";
  return <div className="mt-5 grid gap-3 rounded-[1rem] border border-[var(--template-border)] bg-[var(--template-surface-alt)] p-4 text-[0.69rem] leading-[1.55] text-[var(--template-muted)] sm:grid-cols-2">
    <div className="flex items-start gap-2"><Clock3 className="mt-0.5 h-3.5 w-3.5 shrink-0 text-[var(--template-primary)]" /><span><strong className="font-extrabold text-[var(--template-ink)]">Last verified:</strong> {sourceDate(source)}<br /><span>Official data as of {source?.dataAsOf || "the source page"}.</span></span></div>
    <div className="flex items-start gap-2"><BookOpen className="mt-0.5 h-3.5 w-3.5 shrink-0 text-[var(--template-primary)]" /><span><strong className="font-extrabold text-[var(--template-ink)]">Method:</strong> {stream?.guideVersion || source?.guideVersion || "Current official guidance"}<br /><a className="font-extrabold text-[var(--template-primary)] underline underline-offset-4" href={stream?.sourceUrl || source?.url} target="_blank" rel="noreferrer">Open official source <ExternalLink className="inline h-3 w-3" /></a></span></div>
    <div className="grid gap-3 rounded-[0.9rem] border border-[var(--template-border)] bg-[var(--template-surface)] p-4 sm:col-span-2"><div className="flex items-start gap-2"><Target className="mt-0.5 h-3.5 w-3.5 shrink-0 text-[var(--template-primary)]" /><div><p className="m-0 text-[0.65rem] font-extrabold uppercase tracking-[0.12em] text-[var(--template-primary)]">Pathway essentials</p><p className="m-0 mt-1 text-[0.78rem] font-extrabold text-[var(--template-ink)]">{stream?.label || program.h1Label}</p></div></div><div className="grid gap-2 sm:grid-cols-2"><div className="rounded-[0.75rem] border border-[var(--template-border)] bg-[var(--template-surface-alt)] px-3 py-2.5"><span className="block text-[0.61rem] font-extrabold uppercase tracking-[0.08em] text-[var(--template-muted)]">Tool mode</span><strong className="mt-1 block text-[0.73rem] text-[var(--template-ink)]">{getModeLabel(stream?.mode)}</strong></div><div className="rounded-[0.75rem] border border-[var(--template-border)] bg-[var(--template-surface-alt)] px-3 py-2.5"><span className="block text-[0.61rem] font-extrabold uppercase tracking-[0.08em] text-[var(--template-muted)]">Profile lever</span><strong className="mt-1 block text-[0.73rem] text-[var(--template-ink)]">{improvement}</strong></div></div>{documents.length > 0 && <div className="rounded-[0.75rem] border border-[var(--template-border)] bg-[var(--template-surface-alt)] px-3 py-2.5"><span className="block text-[0.61rem] font-extrabold uppercase tracking-[0.08em] text-[var(--template-muted)]">Evidence focus</span><p className="m-0 mt-1 text-[0.72rem] leading-[1.5] text-[var(--template-ink)]">{documents.join(" · ")}{remainingDocuments > 0 ? ` · +${remainingDocuments} more in the calculator result` : ""}</p></div>}</div>
    {status === "stale" && <div className="flex items-start gap-2 rounded-[0.8rem] border border-amber-400/30 bg-amber-400/10 p-3 text-amber-800 sm:col-span-2"><AlertTriangle className="mt-0.5 h-3.5 w-3.5 shrink-0" /><span><strong className="font-extrabold">Last verified data shown.</strong> The official source has not published a newer verified result in our feed window. Confirm the source before applying.</span></div>}
  </div>;
}

function SnapshotCard({ program }) {
  if (!program.snapshot) return null;
  const status = program.source?.status || "current";
  const stats = getSnapshotStats(program);
  const statGridClass = stats.length > 4 ? "sm:grid-cols-3" : "sm:grid-cols-2";
  return <article className="pnp-snapshot-card relative overflow-hidden rounded-[1.35rem] border border-[color-mix(in_srgb,var(--template-primary)_26%,var(--template-border))] bg-[linear-gradient(145deg,color-mix(in_srgb,var(--cmg-template-deep-surface)_96%,var(--template-primary)),color-mix(in_srgb,var(--template-surface-alt)_88%,var(--template-primary))] p-5 shadow-[0_18px_42px_color-mix(in_srgb,var(--cmg-template-deep-surface)_18%,transparent)] sm:p-7" aria-labelledby="pnp-snapshot-title">
    <div className="pointer-events-none absolute inset-0 opacity-40 [background-image:linear-gradient(color-mix(in_srgb,var(--template-on-primary)_7%,transparent)_1px,transparent_1px),linear-gradient(90deg,color-mix(in_srgb,var(--template-on-primary)_7%,transparent)_1px,transparent_1px),radial-gradient(circle_at_8%_12%,color-mix(in_srgb,var(--template-primary)_23%,transparent),transparent_28%)] [background-size:40px_40px,40px_40px,100%_100%]" aria-hidden="true" />
    <div className="relative">
      <div className="flex flex-wrap items-end justify-between gap-3"><h3 id="pnp-snapshot-title" className="m-0 text-[1.35rem] font-extrabold tracking-[-0.02em] text-[var(--template-on-primary)] sm:text-[1.55rem]">{program.snapshot.title}</h3><StatusBadge status={status}>{status === "stale" ? "Last verified" : "Official snapshot"}</StatusBadge></div>
      <div className={`mt-6 grid grid-cols-2 gap-x-5 gap-y-7 sm:gap-x-10 sm:gap-y-8 ${statGridClass}`}>{stats.map((stat) => <div key={`${stat.value}-${stat.label}`} className="min-w-0"><strong className="block break-words text-[clamp(1.4rem,4.2vw,2.25rem)] font-extrabold leading-[1.05] tracking-[-0.035em] text-[var(--template-on-primary)]">{stat.value}</strong><span className="mt-1.5 block text-[0.78rem] font-extrabold leading-[1.35] text-[color-mix(in_srgb,var(--template-on-primary)_76%,transparent)] sm:text-[0.86rem]">{stat.label}</span></div>)}</div>
      <div className="mt-6 flex flex-wrap items-start justify-between gap-3 border-t border-[color-mix(in_srgb,var(--template-on-primary)_14%,transparent)] pt-4"><p className="m-0 max-w-[48rem] text-[0.68rem] leading-[1.5] text-[color-mix(in_srgb,var(--template-on-primary)_68%,transparent)]">{program.snapshot.note || program.source?.note || "Verify the linked government source before applying."}</p><a href={program.source?.url} target="_blank" rel="noreferrer" className="inline-flex shrink-0 items-center gap-1.5 text-[0.68rem] font-extrabold text-[var(--template-on-primary)] underline underline-offset-4 hover:opacity-80">Verify source <ExternalLink className="h-3.5 w-3.5" /></a></div>
    </div>
  </article>;
}

function DrawContextCard({ program, latest, streamKey }) {
  if (!latest) return null;
  const matchingDraws = (program.draws || []).filter((draw) => !streamKey || draw.streamKey === streamKey);
  const previous = matchingDraws.find((draw) => draw.date !== latest.date) || matchingDraws[1];
  const selection = selectionLabels[latest.selectionType] || "Official selection";
  const scoreBased = latest.selectionType === "score" || latest.selectionType === "score-plus-priority";
  const statusLabel = program.source?.status === "stale" ? "Last verified snapshot" : "Current source snapshot";
  return <article className="mt-4 rounded-[1.15rem] border border-[var(--template-border)] bg-[var(--template-surface-alt)] p-4 sm:p-5" aria-labelledby="pnp-draw-context-title"><div className="flex items-start gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-[0.75rem] bg-[color-mix(in_srgb,var(--template-primary)_12%,transparent)] text-[var(--template-primary)]"><Info className="h-4 w-4" /></div><div><p className="m-0 text-[0.65rem] font-extrabold uppercase tracking-[0.14em] text-[var(--template-primary)]">Round context</p><h4 id="pnp-draw-context-title" className="mt-1 text-[1rem] font-extrabold text-[var(--template-ink)]">How to read this draw</h4></div></div><div className="mt-4 grid gap-2 sm:grid-cols-2"><div className="rounded-[0.8rem] border border-[var(--template-border)] bg-[var(--template-surface)] px-3 py-2.5"><span className="block text-[0.61rem] font-extrabold uppercase tracking-[0.08em] text-[var(--template-muted)]">Selection basis</span><strong className="mt-1 block text-[0.76rem] text-[var(--template-ink)]">{selection}</strong></div><div className="rounded-[0.8rem] border border-[var(--template-border)] bg-[var(--template-surface)] px-3 py-2.5"><span className="block text-[0.61rem] font-extrabold uppercase tracking-[0.08em] text-[var(--template-muted)]">Rounds in this feed</span><strong className="mt-1 block text-[0.76rem] text-[var(--template-ink)]">{matchingDraws.length || 1} published round{matchingDraws.length === 1 ? "" : "s"}</strong></div>{previous && <div className="rounded-[0.8rem] border border-[var(--template-border)] bg-[var(--template-surface)] px-3 py-2.5"><span className="block text-[0.61rem] font-extrabold uppercase tracking-[0.08em] text-[var(--template-muted)]">Previous matching round</span><strong className="mt-1 block text-[0.76rem] text-[var(--template-ink)]">{previous.date}</strong></div>}<div className="rounded-[0.8rem] border border-[var(--template-border)] bg-[var(--template-surface)] px-3 py-2.5"><span className="block text-[0.61rem] font-extrabold uppercase tracking-[0.08em] text-[var(--template-muted)]">Data status</span><strong className="mt-1 block text-[0.76rem] text-[var(--template-ink)]">{statusLabel}</strong></div></div><p className="m-0 mt-3 text-[0.7rem] leading-[1.5] text-[var(--template-muted)]">{scoreBased ? "Use the published cutoff only as a historical benchmark; it does not guarantee the next invitation round." : "This round used targeted or priority selection, so a single score cutoff may not describe every invited profile."}</p></article>;
}

function DrawPanel({ program, streamKey, stream }) {
  const draws = program.draws || [];
  const latest = draws.find((draw) => !streamKey || draw.streamKey === streamKey) || draws[0];
  return <article className="pnp-draw-panel rounded-[1.35rem] border border-[var(--template-border)] bg-[var(--template-surface)] p-5 shadow-[0_18px_42px_color-mix(in_srgb,var(--cmg-template-deep-surface)_12%,transparent)] sm:p-6" aria-labelledby="pnp-draws-title">
    <div className="flex items-start justify-between gap-4"><div><p className="m-0 flex items-center gap-2 text-[0.67rem] font-extrabold uppercase tracking-[0.14em] text-[var(--template-primary)]"><BarChart3 className="h-4 w-4" /> Official selection feed</p><h3 id="pnp-draws-title" className="mt-2 text-[1.25rem] font-extrabold leading-tight text-[var(--template-ink)]">Latest {program.shortName} draw</h3></div><span className="rounded-full border border-[color-mix(in_srgb,var(--template-primary)_26%,var(--template-border))] bg-[color-mix(in_srgb,var(--template-primary)_8%,var(--template-surface-alt))] px-2.5 py-1 text-[0.63rem] font-extrabold uppercase tracking-[0.08em] text-[var(--template-primary)]">{selectionLabels[latest?.selectionType] || "Official"}</span></div>
    {program.isOverview ? <div className="mt-6 rounded-[1rem] border border-dashed border-[var(--template-border)] bg-[var(--template-surface-alt)] p-5"><div className="flex items-start gap-3"><Info className="mt-0.5 h-5 w-5 shrink-0 text-[var(--template-primary)]" /><p className="m-0 text-sm leading-[1.65] text-[var(--template-muted)]">Select a province or territory above to load its official selection history. Canada does not run one national PNP draw.</p></div></div> : latest ? <>
      <div className="mt-6 rounded-[1.05rem] bg-[linear-gradient(135deg,var(--template-primary),var(--template-accent))] p-5 text-[var(--template-on-primary)]"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="m-0 text-[0.66rem] font-extrabold uppercase tracking-[0.12em] opacity-80">Most recent matching round</p><p className="mt-1 text-sm font-extrabold">{latest.date}</p><p className="mt-2 max-w-[30rem] text-[0.86rem] font-extrabold leading-[1.4]">{latest.stream}</p></div><span className="rounded-full border border-white/20 bg-black/10 px-2.5 py-1 text-[0.62rem] font-extrabold uppercase tracking-[0.08em]">{selectionLabels[latest.selectionType] || "Official"}</span></div><DrawFacts draw={latest} featured /></div><DrawContextCard program={program} latest={latest} streamKey={streamKey} />
    </> : <div className="mt-6 rounded-[1rem] border border-dashed border-[var(--template-border)] bg-[var(--template-surface-alt)] p-5 text-sm leading-[1.65] text-[var(--template-muted)]">No public draw row is available for this pathway. Use the official source for the current selection process.</div>}
    <div className="mt-5 border-t border-[var(--template-border)] pt-4"><div className="flex items-start gap-2 text-[0.69rem] leading-[1.5] text-[var(--template-muted)]"><Info className="mt-0.5 h-3.5 w-3.5 shrink-0 text-[var(--template-primary)]" /><p className="m-0">Data as of {program.source?.dataAsOf || "the source page"}. Draw cutoffs are historical signals, not a promise of the next invitation round.</p></div><div className="mt-3 flex flex-wrap items-center gap-x-4 gap-y-2"><a href={stream?.sourceUrl || program.source?.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 text-[0.72rem] font-extrabold text-[var(--template-primary)] underline underline-offset-4 hover:text-[var(--template-accent)]">Open official source <ExternalLink className="h-3.5 w-3.5" /></a>{program.secondarySource && <a href={program.secondarySource.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 text-[0.72rem] font-extrabold text-[var(--template-primary)] underline underline-offset-4 hover:text-[var(--template-accent)]">NWT official source <ExternalLink className="h-3.5 w-3.5" /></a>}</div></div>
  </article>;
}

function FeePanel({ program }) {
  if (!program.feeStages?.length) return null;
  return <article className="pnp-fee-panel rounded-[1.15rem] border border-[var(--template-border)] bg-[var(--template-surface)] p-5 sm:p-6" aria-labelledby="pnp-fees-title"><div className="flex items-start gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-[0.8rem] bg-[color-mix(in_srgb,var(--template-primary)_12%,transparent)] text-[var(--template-primary)]"><ShieldCheck className="h-4 w-4" /></div><div><p className="m-0 text-[0.67rem] font-extrabold uppercase tracking-[0.14em] text-[var(--template-primary)]">Stage-by-stage costs</p><h3 id="pnp-fees-title" className="mt-1 text-[1.1rem] font-extrabold text-[var(--template-ink)]">Fees and timing are separate</h3></div></div><div className="mt-4 grid gap-2">{program.feeStages.map((fee) => <div key={fee.stage} className="flex items-start justify-between gap-4 rounded-[0.8rem] border border-[var(--template-border)] bg-[var(--template-surface-alt)] p-3"><div><p className="m-0 text-[0.75rem] font-extrabold text-[var(--template-ink)]">{fee.stage}</p><p className="m-0 mt-1 text-[0.68rem] leading-[1.45] text-[var(--template-muted)]">{fee.note}</p></div><strong className="shrink-0 text-right text-[0.78rem] text-[var(--template-primary)]">{fee.amount}</strong></div>)}</div></article>;
}

function StatusMessage({ result }) {
  const tone = result.status === "likely-eligible" ? "border-emerald-300/30 bg-emerald-300/10" : result.status === "not-eligible" || result.status === "below-minimum" ? "border-rose-300/30 bg-rose-300/10" : "border-amber-300/30 bg-amber-300/10";
  return <div className={`rounded-[0.95rem] border p-4 text-[0.75rem] leading-[1.55] text-[var(--template-muted)] ${tone}`}><strong className="block text-[0.95rem] text-[var(--template-ink)]">{getStatusLabel(result.status)}</strong>{result.status === "below-minimum" && <span className="mt-1 block">Your calculated score is below the published minimum for this stream. A historical draw cutoff may be higher or may use different selection criteria.</span>}{result.status === "likely-eligible" && <span className="mt-1 block">This indicates a planning fit only. The government verifies documents and may apply priorities or discretionary selection rules.</span>}{result.status === "needs-review" && <span className="mt-1 block">Some answers still need document or program-rule verification before a reliable conclusion is possible.</span>}</div>;
}

function ScoreResult({ program, stream, answers, onRestart }) {
  const result = evaluatePnpStream(stream, answers);
  const latestDraw = program.draws?.find((draw) => draw.streamKey === stream.key);
  return <div className="pnp-calculator-result" aria-live="polite">
    <div className="relative overflow-hidden rounded-[1.15rem] bg-[linear-gradient(135deg,var(--template-primary),var(--template-accent))] p-5 text-[var(--template-on-primary)] sm:p-6"><div className="absolute -right-12 -top-14 h-40 w-40 rounded-full border-[18px] border-[color-mix(in_srgb,var(--template-on-primary)_12%,transparent)]" aria-hidden="true" /><div className="relative flex items-start justify-between gap-4"><div><p className="m-0 flex items-center gap-2 text-[0.67rem] font-extrabold uppercase tracking-[0.13em] opacity-80"><CheckCircle2 className="h-4 w-4" /> Your result</p><h3 className="mt-2 text-[1.18rem] font-extrabold leading-tight">{getStatusLabel(result.status)}</h3></div>{stream.mode === "official-grid" ? <div className="text-right"><strong className="block text-[2.5rem] font-extrabold leading-none">{result.score}</strong><span className="mt-1 block text-[0.62rem] font-extrabold uppercase tracking-[0.08em] opacity-75">of {result.maxScore} points</span></div> : <div className="max-w-[8rem] text-right"><strong className="block text-[1.1rem] font-extrabold leading-tight">No universal score</strong><span className="mt-1 block text-[0.62rem] font-extrabold uppercase tracking-[0.08em] opacity-75">{getModeLabel(stream.mode)}</span></div>}</div><p className="relative mt-4 max-w-[38rem] text-[0.78rem] leading-[1.55] text-[color-mix(in_srgb,var(--template-on-primary)_84%,transparent)]">{stream.focus}</p></div>
    <div className="mt-4"><StatusMessage result={result} /></div>
    {stream.mode === "official-grid" && <div className="mt-4 grid gap-2 sm:grid-cols-2">{result.breakdown.map((item) => <div key={item.section} className="rounded-[0.85rem] border border-[var(--template-border)] bg-[var(--template-surface-alt)] px-3.5 py-3"><div className="flex items-center justify-between gap-3"><span className="text-[0.71rem] font-bold text-[var(--template-muted)]">{item.section}</span><strong className="text-sm text-[var(--template-ink)]">{item.points}/{item.max}</strong></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-[color-mix(in_srgb,var(--template-primary)_10%,var(--template-border))]"><span className="block h-full rounded-full bg-[linear-gradient(90deg,var(--template-primary),var(--template-accent))]" style={{ width: `${item.max ? (item.points / item.max) * 100 : 0}%` }} /></div></div>)}</div>}
    <details className="mt-4 rounded-[0.9rem] border border-[var(--template-border)] bg-[var(--template-surface-alt)] p-4"><summary className="cursor-pointer text-[0.72rem] font-extrabold text-[var(--template-ink)]">Show answer-by-answer audit trail</summary><div className="mt-3 grid gap-2">{result.answerBreakdown.map((item) => <div key={item.key} className="flex items-start justify-between gap-4 border-t border-[var(--template-border)] pt-2 text-[0.7rem] leading-[1.45]"><span className="text-[var(--template-muted)]"><strong className="text-[var(--template-ink)]">{item.label}</strong><br />{item.value}</span>{stream.mode === "official-grid" && <strong className="shrink-0 text-[var(--template-primary)]">+{item.points}</strong>}</div>)}</div></details>
    {(result.failures.length > 0 || result.unknowns.length > 0 || result.missing.length > 0) && <div className="mt-4 grid gap-3 sm:grid-cols-2">{result.failures.length > 0 && <div className="rounded-[0.85rem] border border-rose-300/30 bg-rose-300/10 p-4"><p className="m-0 text-[0.7rem] font-extrabold uppercase tracking-[0.1em] text-rose-800">Rules to resolve</p><ul className="mt-2 pl-4 text-[0.72rem] leading-[1.55] text-[var(--template-muted)]">{result.failures.map((failure) => <li key={failure}>{failure}</li>)}</ul></div>}{(result.unknowns.length > 0 || result.missing.length > 0) && <div className="rounded-[0.85rem] border border-amber-300/30 bg-amber-300/10 p-4"><p className="m-0 text-[0.7rem] font-extrabold uppercase tracking-[0.1em] text-amber-800">Verify before relying on this</p><ul className="mt-2 pl-4 text-[0.72rem] leading-[1.55] text-[var(--template-muted)]">{[...result.unknowns, ...result.missing].map((item) => <li key={item}>{item}</li>)}</ul></div>}</div>}
    {latestDraw && <div className="mt-4 rounded-[0.9rem] border border-[var(--template-border)] bg-[var(--template-surface-alt)] p-4"><p className="m-0 flex items-center gap-2 text-[0.68rem] font-extrabold uppercase tracking-[0.1em] text-[var(--template-primary)]"><BarChart3 className="h-3.5 w-3.5" /> Recent stream signal</p><p className="m-0 mt-2 text-[0.82rem] font-extrabold text-[var(--template-ink)]">{latestDraw.stream}</p><p className="m-0 mt-1 text-[0.71rem] leading-[1.5] text-[var(--template-muted)]">{latestDraw.date} · {latestDraw.minimum === "Not published" ? "No public cutoff" : `Published cutoff ${latestDraw.minimum}`} · {latestDraw.invitations} invitations</p></div>}
    <div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-[0.9rem] border border-[var(--template-border)] bg-[var(--template-surface-alt)] p-4"><p className="m-0 flex items-center gap-2 text-[0.68rem] font-extrabold uppercase tracking-[0.1em] text-[var(--template-primary)]"><FileCheck2 className="h-3.5 w-3.5" /> Evidence to prepare</p><ul className="mt-2 pl-4 text-[0.72rem] leading-[1.55] text-[var(--template-muted)]">{result.documents.map((document) => <li key={document}>{document}</li>)}</ul></div><div className="rounded-[0.9rem] border border-[var(--template-border)] bg-[var(--template-surface-alt)] p-4"><p className="m-0 flex items-center gap-2 text-[0.68rem] font-extrabold uppercase tracking-[0.1em] text-[var(--template-primary)]"><Sparkles className="h-3.5 w-3.5" /> What could improve this</p><ul className="mt-2 pl-4 text-[0.72rem] leading-[1.55] text-[var(--template-muted)]">{stream.improvements.map((item) => <li key={item}>{item}</li>)}</ul></div></div>
    <div className="mt-4 flex items-start gap-2 rounded-[0.85rem] border border-[var(--template-border)] bg-[var(--template-surface-alt)] p-3.5 text-[0.7rem] leading-[1.5] text-[var(--template-muted)]"><Info className="mt-0.5 h-3.5 w-3.5 shrink-0 text-[var(--template-primary)]" /><span>This is a planning result, not a nomination, ITA or legal opinion. Government officers verify your documents and may apply current priorities or selection rules.</span></div>
    <button type="button" onClick={onRestart} className="mt-5 inline-flex items-center gap-2 text-[0.75rem] font-extrabold text-[var(--template-primary)] hover:underline"><RefreshCw className="h-3.5 w-3.5" /> Recalculate</button>
  </div>;
}

function QuestionControl({ question, onChoose, onSubmit }) {
  const [draft, setDraft] = useState("");
  if (question.kind === "number") return <div className="grid gap-3"><label className="grid gap-2"><span className="text-[0.72rem] font-extrabold uppercase tracking-[0.08em] text-[var(--template-muted)]">Enter a value {question.suffix ? `(${question.suffix})` : ""}</span><input autoFocus type="number" min={question.min} max={question.max} step={question.step || 1} value={draft} onChange={(event) => setDraft(event.target.value)} className="h-[3.8rem] w-full rounded-[0.9rem] border border-[var(--template-border)] bg-[var(--template-surface-alt)] px-4 text-lg font-extrabold text-[var(--template-ink)] outline-none focus:border-[var(--template-primary)] focus:ring-2 focus:ring-[color-mix(in_srgb,var(--template-primary)_18%,transparent)]" /></label>{question.help && <p className="m-0 text-[0.7rem] leading-[1.5] text-[var(--template-muted)]">{question.help}</p>}<button type="button" onClick={() => onSubmit(draft)} disabled={draft === ""} className="inline-flex min-h-[3.25rem] items-center justify-center gap-2 rounded-[0.8rem] bg-[var(--template-primary)] px-4 text-[0.78rem] font-extrabold text-[var(--template-on-primary)] disabled:cursor-not-allowed disabled:opacity-45">Continue <ArrowRight className="h-4 w-4" /></button></div>;
  return <div className="grid gap-2.5 sm:grid-cols-2">{question.options.map((optionItem) => <ToolOptionButton key={optionItem.value} onClick={() => onChoose(optionItem.value)} className="min-h-[3.65rem] text-[0.78rem]"><span className="text-left">{optionItem.label}</span><ArrowRight className="h-4 w-4 shrink-0 text-[var(--template-primary)]" /></ToolOptionButton>)}</div>;
}

function CalculatorPanel({ program, initialStreamKey }) {
  const [streamKey, setStreamKey] = useState(initialStreamKey || program.streams?.[0]?.key || "");
  const stream = useMemo(() => getStream(program, streamKey), [program, streamKey]);
  const [answers, setAnswers] = useState({});
  const [step, setStep] = useState(0);
  const [complete, setComplete] = useState(false);
  const questions = stream?.questions || [];
  const question = questions[step];
  const calculatorTitle = stream?.mode === "official-grid" ? `${program.shortName} points calculator` : stream?.mode === "eligibility-planner" ? `${program.shortName} eligibility planner` : `${program.shortName} official pathway guide`;
  const calculatorKicker = stream?.mode === "official-grid" ? "Official points grid" : stream?.mode === "eligibility-planner" ? "Official eligibility" : "Official pathway guide";

  const restart = () => { setAnswers({}); setStep(0); setComplete(false); };
  const changeStream = (event) => { setStreamKey(event.target.value); setAnswers({}); setStep(0); setComplete(false); };
  const advance = (value) => { if (!question) return; const nextAnswers = { ...answers, [question.key]: value }; setAnswers(nextAnswers); if (step === questions.length - 1) setComplete(true); else setStep((current) => current + 1); };

  return <ToolCard className="pnp-calculator-card h-full" aria-labelledby="pnp-calculator-title"><ToolHeader icon={Calculator} kicker={calculatorKicker} title={calculatorTitle} subtitle={stream?.focus || program.focus} action={!complete ? <div className="max-[620px]:hidden"><ToolResetButton onClick={restart}><RefreshCw className="h-3.5 w-3.5" /> Reset</ToolResetButton></div> : null} /><div className="flex flex-1 flex-col p-5 sm:p-6">
    {program.streams?.length > 1 ? <label className="grid gap-2"><span className="text-[0.68rem] font-extrabold uppercase tracking-[0.1em] text-[var(--template-muted)]">1. Choose the exact stream first</span><select value={streamKey} onChange={changeStream} className="h-[3.15rem] rounded-[0.8rem] border border-[var(--template-border)] bg-[var(--template-surface-alt)] px-3 text-sm font-bold text-[var(--template-ink)] outline-none focus:border-[var(--template-primary)] focus:ring-2 focus:ring-[color-mix(in_srgb,var(--template-primary)_18%,transparent)]">{(program.streams || []).map((item) => <option key={item.key} value={item.key}>{item.label}</option>)}</select></label> : <div className="grid gap-1 rounded-[0.8rem] border border-[var(--template-border)] bg-[color-mix(in_srgb,var(--template-primary)_6%,var(--template-surface-alt))] px-4 py-3"><span className="text-[0.62rem] font-extrabold uppercase tracking-[0.14em] text-[var(--template-muted)]">Pathway</span><strong className="text-sm text-[var(--template-ink)]">{stream?.label}</strong></div>}
    {stream && <div className="mt-3 flex flex-wrap items-center gap-2"><span className="rounded-full bg-[color-mix(in_srgb,var(--template-primary)_10%,var(--template-surface-alt))] px-2.5 py-1 text-[0.62rem] font-extrabold uppercase tracking-[0.08em] text-[var(--template-primary)]">{getModeLabel(stream.mode)}</span>{stream.minimumScore != null && <span className="text-[0.68rem] font-semibold text-[var(--template-muted)]">Minimum published score: {stream.minimumScore}</span>}</div>}
    {stream?.mode === "no-calculator" ? <div className="mt-7 rounded-[1rem] border border-dashed border-[var(--template-border)] bg-[var(--template-surface-alt)] p-5"><div className="flex items-start gap-3"><BookOpen className="mt-0.5 h-5 w-5 shrink-0 text-[var(--template-primary)]" /><div><h3 id="pnp-calculator-title" className="m-0 text-base font-extrabold text-[var(--template-ink)]">Use the official stream guide</h3><p className="mt-2 text-[0.78rem] leading-[1.6] text-[var(--template-muted)]">The government does not publish a reproducible public calculator for this stream. We will not invent a score.</p><a className="mt-4 inline-flex items-center gap-2 text-[0.75rem] font-extrabold text-[var(--template-primary)] underline underline-offset-4" href={stream.sourceUrl} target="_blank" rel="noreferrer">Open official guide <ExternalLink className="h-3.5 w-3.5" /></a></div></div></div> : complete ? <ScoreResult program={program} stream={stream} answers={answers} onRestart={restart} /> : questions.length ? <>
      <div className="mt-7 flex items-end gap-3"><div className="min-w-0 flex-1"><ToolProgress value={step} max={questions.length} labelLeft={`Question ${step + 1} of ${questions.length}`} labelRight={`${Math.round((step / questions.length) * 100)}%`} /></div><button type="button" onClick={restart} className="shrink-0 text-[0.7rem] font-extrabold text-[var(--template-muted)] hover:text-[var(--template-primary)] min-[621px]:hidden">Reset</button></div><div className="mt-7"><h3 id="pnp-calculator-title" className="m-0 text-[1.17rem] font-extrabold leading-[1.25] text-[var(--template-ink)]">{question.label}</h3>{question.help && <p className="mt-2 text-[0.72rem] leading-[1.5] text-[var(--template-muted)]">{question.help}</p>}<div className="mt-5"><QuestionControl key={question.key} question={question} onChoose={advance} onSubmit={advance} /></div></div><div className="mt-auto flex items-center justify-between gap-4 pt-7">{step > 0 ? <button type="button" onClick={() => setStep((current) => current - 1)} className="inline-flex items-center gap-1.5 text-[0.72rem] font-extrabold text-[var(--template-muted)] hover:text-[var(--template-primary)]"><ArrowLeft className="h-3.5 w-3.5" /> Back</button> : <span /> }<p className="m-0 flex items-center gap-1.5 text-right text-[0.66rem] leading-[1.35] text-[var(--template-muted)]"><Target className="h-3.5 w-3.5 shrink-0 text-[var(--template-primary)]" /> Built for {program.regionLabel}</p></div>
    </> : <div className="mt-7 rounded-[1rem] border border-dashed border-[var(--template-border)] bg-[var(--template-surface-alt)] p-5 text-sm leading-[1.65] text-[var(--template-muted)]">This pathway has no public calculator. Review the official guide and prepare the evidence listed above.</div>}
  </div></ToolCard>;
}

export default function PnpProgramExperience({ program }) {
  const [selectedKey, setSelectedKey] = useState(program.isOverview ? "bc" : program.key);
  const activeProgram = program.isOverview ? PNP_PROGRAMS[selectedKey] : program;
  const firstStream = activeProgram.streams?.[0];
  return <section className="pnp-program-experience" aria-labelledby="pnp-experience-title"><div className="rounded-[1.55rem] border border-[var(--template-border)] bg-[linear-gradient(145deg,color-mix(in_srgb,var(--template-primary)_7%,var(--template-surface-alt)),var(--template-surface-alt))] p-4 shadow-[0_24px_68px_color-mix(in_srgb,var(--cmg-template-deep-surface)_12%,transparent)] sm:p-6 lg:p-8">
    <div className="flex flex-col justify-between gap-5 border-b border-[var(--template-border)] pb-6 lg:flex-row lg:items-end"><div className="max-w-[49rem]"><p className="m-0 flex items-center gap-2 text-[0.67rem] font-extrabold uppercase tracking-[0.15em] text-[var(--template-primary)]"><MapPin className="h-4 w-4" /> Official program decision support</p><h2 id="pnp-experience-title" className="mt-2 text-[clamp(1.65rem,3vw,2.35rem)] font-extrabold leading-[1.08] tracking-[-0.03em] text-[var(--template-ink)]">See the latest draw signal, then test your profile</h2><p className="mt-3 max-w-[44rem] text-[0.9rem] leading-[1.65] text-[var(--template-muted)]">Choose the exact pathway first. Numeric scores appear only where the government publishes a reproducible grid; other pathways use an official eligibility and priority planner.</p></div>{program.isOverview && <label className="grid min-w-0 gap-2 lg:w-[18rem]"><span className="text-[0.68rem] font-extrabold uppercase tracking-[0.1em] text-[var(--template-muted)]">Choose a program</span><select value={selectedKey} onChange={(event) => setSelectedKey(event.target.value)} className="h-[3.1rem] rounded-[0.8rem] border border-[var(--template-border)] bg-[var(--template-surface)] px-3 text-sm font-bold text-[var(--template-ink)] outline-none focus:border-[var(--template-primary)] focus:ring-2 focus:ring-[color-mix(in_srgb,var(--template-primary)_18%,transparent)]">{PNP_PROGRAM_OPTIONS.map((optionItem) => <option key={optionItem.key} value={optionItem.key}>{optionItem.label}</option>)}</select></label>}</div>
    <div className="mt-6"><SnapshotCard program={program.isOverview ? program : activeProgram} /></div>
    <div className="mt-6 grid gap-5 xl:grid-cols-[minmax(0,1.05fr)_minmax(360px,.95fr)]"><DrawPanel program={activeProgram} streamKey={firstStream?.key} stream={firstStream} /><CalculatorPanel key={activeProgram.key} program={activeProgram} initialStreamKey={firstStream?.key} /></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-2"><FeePanel program={activeProgram} /><SourceMeta program={activeProgram} stream={firstStream} /></div>
    <p className="mt-5 flex items-start gap-2 text-[0.68rem] leading-[1.5] text-[var(--template-muted)]"><Info className="mt-0.5 h-3.5 w-3.5 shrink-0 text-[var(--template-primary)]" /> Government rules, allocations and draw patterns can change without notice. This tool is for planning only; it does not create an application, nomination or client relationship.</p>
  </div></section>;
}
